temperature_monitor/urls.py
from django.urls import path

from . import views


app_name = 'temperature_monitor'

urlpatterns = [
    path('', views.home, name='home'),
    path('gateways/', views.GatewayList.as_view(), name='gateway_list'),
    path('gateways/<int:pk>/', views.GatewayDetail.as_view(), name='gateway_detail'),
    path('queries/', views.QueryList.as_view(), name='query_list'),
    path('sensors/', views.SensorList.as_view(), name='sensor_list'),
    path('sensors/<int:pk>/', views.SensorDetail.as_view(), name='sensor_detail'),
    path('update/', views.update, name='update'),
]

temperature_monitor/models.py
import datetime
import pytz

from django.conf import settings
from django.db import models

import humanize


def convert_c_to_f(temperature):
    if temperature is None:
        return None
    else:
        return 9 * temperature / 5 + 32


def pretty_range(alert_min, alert_max, alert_type='temperature'):
    unit = ''
    if alert_type == 'temperature':
        unit = getattr(settings, 'TEMPERATURE_MONITOR_UNIT', 'C')
        if unit is 'F':
            alert_min = convert_c_to_f(alert_min)
            alert_max = convert_c_to_f(alert_max)
        unit = ' °{}'.format(unit)
    elif alert_type == 'humidity':
        unit = '%'

    if alert_min is None and alert_max is None:
        return '-'
    elif alert_min is None:
        return '≤ {}{}'.format(alert_max, unit)
    elif alert_max is None:
        return '≥ {}{}'.format(alert_min, unit)
    else:
        return '{}{} to {}{}'.format(
            alert_min, unit, alert_max, unit)


class Gateway(models.Model):
    serial_number = models.CharField(
        help_text='',
        max_length=30,
        unique=True,
    )
    last_seen = models.DateTimeField(
        blank=True,
        help_text='Time gateway was last seen.',
        null=True,
    )
    _timezone = models.CharField(
        blank=True,
        help_text='Gateway\'s current time zone.',
        max_length=30,
        null=True,
    )

    def __str__(self):
        return self.serial_number

    @property
    def active_sensors_count(self):
        return self.sensors.filter(active=True).count()

    @property
    def alert(self):
        return self.time_since_alert_a or self.time_since_alert_b

    @property
    def inactive_sensors_count(self):
        return self.sensors.filter(active=False).count()

    @property
    def time_since_alert_a(self):
        return self.timedelta > datetime.timedelta(seconds=60*60*0.5)

    @property
    def time_since_alert_b(self):
        return self.timedelta > datetime.timedelta(seconds=60*60*3)

    @property
    def time_since_last_seen(self):
        return humanize.naturaltime(self.timedelta)

    @property
    def timedelta(self):
        now = datetime.datetime.now(pytz.timezone(self.timezone))
        if self.last_seen:
            return now - self.last_seen
        else:
            return None

    @property
    def timezone(self):
        if self._timezone:
            return self._timezone
        else:
            return settings.TIME_ZONE


class Query(models.Model):
    time = models.DateTimeField(
        blank=True,
        help_text='Time query started.',
        null=True,
        unique=True,
    )
    gateway_count = models.PositiveSmallIntegerField(
        default=0,
        help_text='Number of gateways queried.',
    )
    sensor_count = models.PositiveSmallIntegerField(
        default=0,
        help_text='Number of sensors queried.',
    )
    timepoint_count = models.PositiveSmallIntegerField(
        default=0,
        help_text='Number of timepoints queried.',
    )
    duration = models.DurationField(
        blank=True,
        help_text='Duration of query (seconds).',
        null=True,
    )

    def __str__(self):
        return str(self.time)

    @property
    def alert(self):
        return (self.gateway_alert or self.query_alert or self.sensor_alert
            or self.timepoint_alert)

    @property
    def gateway_alert(self):
        return self.gateway_count == 0

    @property
    def query_alert(self):
        return self.duration is None

    @property
    def sensor_alert(self):
        return self.sensor_count == 0

    @property
    def timedelta(self):
        now = datetime.datetime.now(pytz.timezone(settings.TIME_ZONE))
        return now - self.time

    @property
    def time_since(self):
        return humanize.naturaltime(self.timedelta)

    @property
    def timepoint_alert(self):
        return self.timepoint_count == 0

    class Meta:
        get_latest_by = ['time']
        ordering = ['-time']


class Sensor(models.Model):
    device_type = models.CharField(
        help_text='Sensor type.',
        max_length=15,
    )
    location = models.CharField(
        help_text='Name and/or location of sensor.',
        max_length=20,
    )
    serial_number = models.CharField(
        help_text='',
        max_length=30,
        unique=True,
    )
    gateway = models.ForeignKey(
        'Gateway',
        blank=True,
        help_text='Gateway this sensor is connected to.',
        null=True,
        on_delete=models.SET_NULL,
        related_name='sensors',
    )
    active = models.BooleanField(
        default=True,
    )

    battery = models.CharField(
        blank=True,
        help_text='',
        max_length=7,
        null=True,
    )
    link = models.CharField(
        blank=True,
        help_text='',
        max_length=5,
        null=True,
    )

    humidity_alert_min_unitless = models.SmallIntegerField(
        blank=True,
        help_text='',
        null=True,
    )
    humidity_alert_max_unitless = models.SmallIntegerField(
        blank=True,
        help_text='',
        null=True,
    )
    probe_alert_min_celsius_unitless = models.SmallIntegerField(
        blank=True,
        help_text='',
        null=True,
    )
    probe_alert_max_celsius_unitless = models.SmallIntegerField(
        blank=True,
        help_text='',
        null=True,
    )
    sensor_alert_min_celsius_unitless = models.SmallIntegerField(
        blank=True,
        help_text='',
        null=True,
    )
    sensor_alert_max_celsius_unitless = models.SmallIntegerField(
        blank=True,
        help_text='',
        null=True,
    )

    def __str__(self):
        return self.location

    @property
    def alert(self):
        return self.alert_environment or self.alert_time

    @property
    def alert_environment(self):
        return self.humidity_alert or self.probe_alert or self.sensor_alert

    @property
    def alert_time(self):
        return self.time_since_alert_a or self.time_since_alert_b

    @property
    def humidity(self):
        return self.timepoints.latest().humidity

    @property
    def humidity_alert(self):
        try:
            humidity = self.timepoints.latest().humidity_unitless
        except:
            humidity = None
        low = float(self.humidity_alert_min_unitless or '-inf')
        high = float(self.humidity_alert_max_unitless or 'inf')
        if humidity and not low <= float(humidity) <= high:
            return True
        else:
            return False

    @property
    def humidity_range(self):
        return pretty_range(
            self.humidity_alert_min_unitless,
            self.humidity_alert_max_unitless,
            alert_type='humidity')

    @property
    def last_seen(self):
        return self.timepoints.latest().time

    @property
    def probe_alert(self):
        try:
            temp = self.timepoints.latest().probe_celsius_unitless
        except:
            temp = None
        low = float(self.probe_alert_min_celsius_unitless or '-inf')
        high = float(self.probe_alert_max_celsius_unitless or 'inf')
        if temp and not low <= float(temp) <= high:
            return True
        else:
            return False

    @property
    def probe_range(self):
        return pretty_range(
            self.probe_alert_min_celsius_unitless,
            self.probe_alert_max_celsius_unitless)

    @property
    def probe_temp(self):
        if getattr(settings, 'TEMPERATURE_MONITOR_UNIT', 'C') is 'F':
            return self.timepoints.latest().probe_farhenheit
        else:
            return self.timepoints.latest().probe_celsius

    @property
    def sensor_alert(self):
        try:
            temp = self.timepoints.latest().sensor_celsius_unitless
        except:
            temp = None
        low = float(self.sensor_alert_min_celsius_unitless or '-inf')
        high = float(self.sensor_alert_max_celsius_unitless or 'inf')
        if temp and not low <= float(temp) <= high:
            return True
        else:
            return False

    @property
    def sensor_range(self):
        return pretty_range(
            self.sensor_alert_min_celsius_unitless,
            self.sensor_alert_max_celsius_unitless)

    @property
    def sensor_temp(self):
        if getattr(settings, 'TEMPERATURE_MONITOR_UNIT', 'C') is 'F':
            return self.timepoints.latest().sensor_farhenheit
        else:
            return self.timepoints.latest().sensor_celsius

    @property
    def time_since_last_seen(self):
        return self.timepoints.latest().time_since

    @property
    def time_since_alert_a(self):
        return self.timedelta > datetime.timedelta(seconds=60*60*3)

    @property
    def time_since_alert_b(self):
        return self.timedelta > datetime.timedelta(seconds=60*60*12)

    @property
    def timedelta(self):
        try:
            timedelta = self.timepoints.latest().timedelta
        except:
            timedelta = datetime.timedelta()
        return timedelta

    @property
    def timezone(self):
        if self.gateway and self.gateway.timezone:
            return self.gateway.timezone
        else:
            return settings.TIME_ZONE

    class Meta:
        ordering = ['location']


class TimePoint(models.Model):
    sensor = models.ForeignKey(
        'Sensor',
        help_text='Sensor that collected this record.',
        related_name='timepoints',
        on_delete=models.PROTECT,
    )
    time = models.DateTimeField(
        help_text='Time data were collected.',
    )

    humidity_unitless = models.DecimalField(
        blank=True,
        decimal_places=1,
        help_text='Sensor percent humidity '
            '(enter the number only, no units).',
        max_digits=4,
        null=True,
    )
    probe_celsius_unitless = models.DecimalField(
        blank=True,
        decimal_places=1,
        help_text='Probe termperature in Celsius '
            '(enter the number only, no units).',

temperature_monitor/templates/temperature_monitor/_messages.html
<div class="container">
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
</div>

temperature_monitor/templates/temperature_monitor/_update.html
<form id="update-la-crosse-alerts" action="{% url 'temperature_monitor:update' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ request.path }}">
  <div class="form-group inline-form-buttons">
    <button type="submit" class="btn btn-sm btn-success py-0 {% if latest_query and latest_query.timedelta.total_seconds < update_delay %}disabled{% endif %}">
      Update{% if latest_query and latest_query.timedelta.total_seconds < update_delay %}d{% endif %}
    </button>
  </div>
</form>

temperature_monitor/templates/temperature_monitor/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <title>{% block title %}Temperature Monitor{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'temperature_monitor/css/app.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    {% block header %}{% endblock header %}
  </head>

  <body>
    <br>
    {% include "temperature_monitor/_messages.html" %}
    {% block content %}{% endblock %}
    {% if latest_query %}
      <div class="container">
        <span class="float-right"><small><em>Last Update: {{ latest_query.time_since }}</em></small></span>
      </div>
    {% endif %}
    <br>
    <br>
    <br>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static 'temperature_monitor/js/app.js' %}"></script>
    {% block footer %}{% endblock %}
  </body>
</html>

temperature_monitor/templates/temperature_monitor/gateway_list.html
{% extends "temperature_monitor/base.html" %}
{% load project_home %}

{% block title %}Gateways | {{ block.super }}{% endblock %}

{% block content %}
  <div class="container">

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {% project_home_breadcrumb_bs4 %}
        <li class="breadcrumb-item active" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:home' %}">Temperature Monitor</a></li>
        <li class="breadcrumb-item active" aria-label="breadcrumb" aria-current="page">Gateways</li>
      </ol>
    </nav>

    {% if perms.temperature_monitor.add_sensor %}
      <span class="float-right ml-2 mb-0 pb-0">{% include "temperature_monitor/_update.html" %}</span>
    {% endif %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" class="text-left">Serial Number</th>
          <th scope="col" class="text-center">Time Since Last Seen</th>
          <th scope="col" class="text-center"># of Active Sensors</th>
          <th scope="col" class="text-center d-none d-sm-table-cell d-print-table-cell"># of Inactive Sensors</th>
          <th scope="col" class="text-center d-none d-sm-table-cell d-print-table-cell">Time Zone</th>
        </tr>
      </thead>
      <tbody>
        {% for gateway in gateway_list %}
          <tr class="clickable-row" data-href="{% url 'temperature_monitor:gateway_detail' gateway.pk %}">
            <th scope="row" class="text-left">{{ gateway.serial_number }}</th>
            <td class="text-center {% if gateway.time_since_alert_b %}bg-danger text-light{% elif gateway.time_since_alert_a %}bg-warning{% endif %}">{{ gateway.last_seen|timesince }}</td>
            <td class="text-center">{{ gateway.active_sensors_count|default:"-" }}</td>
            <td class="text-center d-none d-sm-table-cell d-print-table-cell">{{ gateway.inactive_sensors_count|default:"-" }}</td>
            <td class="text-center d-none d-sm-table-cell d-print-table-cell">{{ gateway.timezone|default:"-" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock content %}

{% block footer %}
  <script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
  </script>
{% endblock footer %}

temperature_monitor/templates/temperature_monitor/home.html
{% extends "temperature_monitor/base.html" %}
{% load humanize project_home staticfiles %}

{% block title %}Home | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="container">

    {% project_home_url as project_home_url %}
    {% if project_home_url %}
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          {% project_home_breadcrumb_bs4 %}
          <li class="breadcrumb-item active" aria-label="breadcrumb" aria-current="page">Temperature Monitor</li>
        </ol>
      </nav>
    {% endif %}

    <div class="card text-dark bg-light mb-3 text-center">

      <div class="card-body">
        <h1 class="card-title mb-4">
          Temperature Monitor
        </h1>
        <div class="row">

          <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="card {% if sensor_alert_environment %}bg-danger{% elif sensor_alert_time %}bg-warning{% else %}bg-primary{% endif %} mb-4">
              <a href="{% url 'temperature_monitor:sensor_list' %}" class="card-link {% if sensor_alert_environment %}text-light{% elif sensor_alert_time %}text-primary{% else %}text-light{% endif %}">
                <div class="card-body">
                  <h4 class="card-title text-center my-5">{{ active_sensor_count }} Sensor{{ active_sensor_count|pluralize }}</h4>
                </div>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="card {% if gateway_alert %}bg-danger{% else %}bg-primary{% endif %} mb-4">
              <a href="{% url 'temperature_monitor:gateway_list' %}" class="card-link text-light">
                <div class="card-body">
                  <h4 class="card-title text-center my-5">{{ gateway_count }} Gateway{{ gateway_count|pluralize }}</h4>
                </div>
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="card {% if query_alert %}bg-danger{% else %}bg-primary{% endif %} mb-4">
              <a href="{% url 'temperature_monitor:query_list' %}" class="card-link text-light">
                <div class="card-body">
                  <h4 class="card-title text-center my-5">{{ query_count|intcomma }} Quer{{ query_count|pluralize:"y,ies" }}</h4>
                </div>
              </a>
            </div>
          </div>

          {% if perms.temperature_monitor.add_sensor %}
            <div class="col-lg-3 col-md-4 col-sm-6">
              <div class="card bg-info mb-4">
                {% if latest_query and latest_query.timedelta.total_seconds < update_delay %}
                  <div class="card-body text-light updated">
                    <h4 class="card-title text-center my-5">Updated</h4>
                  </div>
                {% else %}
                  <a href="{% url 'temperature_monitor:update' %}" class="card-link text-light">
                    <div class="card-body">
                      <h4 class="card-title text-center my-5">Update</h4>
                    </div>
                  </a>
                {% endif %}
              </div>
            </div>
          {% endif %}

        </div>
      </div>

    </div>
  </div>
{% endblock content %}

temperature_monitor/templates/temperature_monitor/query_list.html
{% extends "temperature_monitor/base.html" %}
{% load project_home %}

{% block title %}Queries | {{ block.super }}{% endblock %}

{% block content %}
  <div class="container">

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {% project_home_breadcrumb_bs4 %}
        <li class="breadcrumb-item active" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:home' %}">Temperature Monitor</a></li>
        <li class="breadcrumb-item active" aria-label="breadcrumb" aria-current="page">Query Log</li>
      </ol>
    </nav>

    {% if perms.temperature_monitor.add_sensor %}
      <span class="float-right ml-2 mb-0 pb-0">{% include "temperature_monitor/_update.html" %}</span>
    {% endif %}
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th scope="col" class="text-left">Time</th>
          <th scope="col" class="text-center d-none d-lg-table-cell d-print-table-cell">Time Since</th>
          <th scope="col" class="text-center d-none d-md-table-cell d-print-table-cell">Duration (s)</th>
          <th scope="col" class="text-center">Gateways</th>
          <th scope="col" class="text-center">Sensors</th>
          <th scope="col" class="text-center">Timepoints</th>
        </tr>
      </thead>
      <tbody>
        {% for query in query_list|slice:":100" %}
          <tr>
            <th scope="row" class="text-left">
              {{ query.time|time }}
              {% ifchanged %}- {{ query.time|date }}{% endifchanged %}
            </th>
            <td class="text-center d-none d-lg-table-cell d-print-table-cell">{{ query.time_since }}</td>
            <td class="text-center d-none d-md-table-cell d-print-table-cell  {% if query.query_alert %}bg-danger text-light{% endif %}">{{ query.duration.total_seconds|default:"-" }}</td>
            <td class="text-center {% if query.gateway_alert %}bg-danger text-light{% endif %}">{{ query.gateway_count }}</td>
            <td class="text-center {% if query.sensor_alert %}bg-danger text-light{% endif %}">{{ query.sensor_count }}</td>
            <td class="text-center {% if query.timepoint_alert %}bg-danger text-light{% endif %}">{{ query.timepoint_count }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock content %}

temperature_monitor/templates/temperature_monitor/sensor_detail.html
{% extends "temperature_monitor/base.html" %}
{% load project_home %}

{% block title %}{{ sensor }} | {{ block.super }}{% endblock %}

{% block content %}
  <div class="container">

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {% project_home_breadcrumb_bs4 %}
        <li class="breadcrumb-item active" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:home' %}">Temperature Monitor</a></li>
        {% if gateway %}
          <li class="breadcrumb-item" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:gateway_list' %}">Gateways</a></li>
          <li class="breadcrumb-item" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:gateway_detail' gateway.pk %}">{{ gateway.serial_number }}</a></li>
        {% else %}
          <li class="breadcrumb-item" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:sensor_list' %}">Sensors</a></li>
        {% endif %}
        <li class="breadcrumb-item active" aria-label="breadcrumb" aria-current="page">{{ sensor }}</li>
      </ol>
    </nav>

    {% if perms.temperature_monitor.add_sensor %}
      <div class="container">
        <div class="row justify-content-md-end">
          {% include "temperature_monitor/_update.html" %}
        </div>
      </div>
    {% endif %}

    <div class="card mb-3">
      <div class="card-header bg-dark text-light">
        <h5 class="card-title mb-0">
          <div class="btn-group btn-group-sm float-right mb-1" role="group" aria-label="">
            {% if perms.temperature_monitor.change_sensor %}
              <a href="{% url 'admin:temperature_monitor_sensor_change' sensor.pk %}" class="btn btn-primary py-0">
                <span class="d-none d-md-inline">Edit Sensor</span><span class="d-md-none">Edit</span>
              </a>
            {% endif %}
            <a href="http://www.lacrossealertsmobile.com/v1.2/#device-{{ sensor.serial_number }}" target="_blank" class="btn btn-info py-0">
              <span class="d-none d-md-inline">La Crosse Alerts Mobile</span><span class="d-md-none">La Crosse</span>
            </a>
          </div>
          {{ sensor.location }} {% if not sensor.active %}<span class="text-danger"><small>INACTIVE</small></span>{% endif %}
        </h5>
      </div>
      <div class="card-body {% if not sensor.active %}bg-secondary{% endif %}">
        {% if sensor.probe_range != "-" %}
          <p class="mb-2"><strong>Probe Range:</strong> {{ sensor.probe_range }}</p>
        {% endif %}
        {% if sensor.sensor_range != "-" %}
          <p class="mb-2"><strong>Sensor Range:</strong> {{ sensor.sensor_range }}</p>
        {% endif %}
        {% if sensor.humidity_range != "-" %}
          <p class="mb-2"><strong>Humidity Range:</strong> {{ sensor.humidity_range }}</p>
        {% endif %}
        <p class="mb-2"><strong>Battery:</strong> {{ sensor.battery }}</p>
        <p class="mb-2"><strong>Link:</strong> {{ sensor.link }}</p>
      </div>
    </div>

    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th scope="col" class="text-left">Time</th>
          <th scope="col" class="text-center">Probe Temp</th>
          <th scope="col" class="text-center">Sensor Temp</th>
          <th scope="col" class="text-center">Humidity</th>
          <th scope="col" class="text-center d-none d-md-table-cell d-print-table-cell"> Time Since</th>
        </tr>
      </thead>
      <tbody>
        {% for timepoint in sensor.timepoints.all|slice:":100" %}
          <tr>
            <td scope="row" class="text-left">
              {{ timepoint.time|time }}
              {% ifchanged %}- {{ timepoint.time|date }}{% endifchanged %}
            </td>
            <td class="text-center">{{ timepoint.probe_celsius|default:"-" }}</td>
            <td class="text-center">{{ timepoint.sensor_celsius|default:"-" }}</td>
            <td class="text-center">{{ timepoint.humidity|default:"-" }}</td>
            <td class="text-center d-none d-md-table-cell d-print-table-cell">{{ timepoint.time|timesince }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock content %}

temperature_monitor/templates/temperature_monitor/sensor_list.html
{% extends "temperature_monitor/base.html" %}
{% load project_home %}

{% block title %}Sensors | {{ block.super }}{% endblock %}

{% block content %}
  <div class="container">

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {% project_home_breadcrumb_bs4 %}
        <li class="breadcrumb-item active" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:home' %}">Temperature Monitor</a></li>
        {% if gateway %}
          <li class="breadcrumb-item" aria-label="breadcrumb"><a href="{% url 'temperature_monitor:gateway_list' %}">Gateways</a></li>
          <li class="breadcrumb-item active" aria-label="breadcrumb" aria-current="page">{{ gateway.serial_number }}</li>
        {% else %}
          <li class="breadcrumb-item active" aria-label="breadcrumb" aria-current="page">Sensors</li>
        {% endif %}
      </ol>
    </nav>

    {% if perms.temperature_monitor.add_sensor %}
      <span class="float-right ml-2 mb-0 pb-0">{% include "temperature_monitor/_update.html" %}</span>
    {% endif %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" class="text-left">Location</th>
          <th scope="col" class="text-center">Time Since Last Seen</th>
          <th scope="col" class="text-center">Probe Temp</th>
          <th scope="col" class="text-center">Probe Range</th>
          <th scope="col" class="text-center d-none d-sm-table-cell d-print-table-cell">Battery</th>
          <th scope="col" class="text-center d-none d-md-table-cell d-print-table-cell">Link</th>
          <th scope="col" class="text-center d-none d-md-table-cell d-print-table-cell">Sensor Temp</th>
          <th scope="col" class="text-center d-none d-md-table-cell d-print-table-cell">Humidity</th>
        </tr>
      </thead>
      <tbody>
        {% for sensor in sensor_list %}
          <tr class="clickable-row" data-href="{% url 'temperature_monitor:sensor_detail' sensor.pk %}{% if gateway %}?gateway_pk={{ gateway.pk }}{% endif %}">
            <th scope="row" class="text-left">{{ sensor }}</th>
            <td class="text-center {% if sensor.time_since_alert_b %}bg-danger text-light{% elif sensor.time_since_alert_a %}bg-warning{% endif %}">{{ sensor.last_seen|timesince }}</td>
            <td class="text-center {% if sensor.probe_alert %}bg-danger text-light{% endif %}">{{ sensor.probe_temp|default:"-" }}</td>
            <td class="text-center {% if sensor.probe_alert %}bg-danger text-light{% endif %}">{{ sensor.probe_range }}</td>
            <td class="text-center d-none d-sm-table-cell d-print-table-cell {% if sensor.battery != 'Good' %}bg-danger text-light{% endif %}">{{ sensor.battery|default:"-" }}</td>
            <td class="text-center d-none d-md-table-cell d-print-table-cell">{{ sensor.link|default:"-" }}</td>
            <td class="text-center d-none d-md-table-cell d-print-table-cell {% if sensor.sensor_alert %}bg-danger text-light{% endif %}">{{ sensor.sensor_temp|default:"-" }}</td>
            <td class="text-center d-none d-md-table-cell d-print-table-cell {% if sensor.humidity_alert %}bg-danger text-light{% endif %}">{{ sensor.humidity|default:"-" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock content %}

{% block footer %}
  <script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
  </script>
{% endblock footer %}